apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-website-deployment
  namespace: default
  labels:
    app: home-website-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-website-app
  template:
    metadata:
      labels:
        app: home-website-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: home-website-deployment
          image: samsja/samsja-cloud-home-website:pi
          imagePullPolicy: Always
          ports:
          - containerPort: 5000


          livenessProbe:
            httpGet:
              path: /
              port: 5000
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            periodSeconds: 2


          # resources:
          #   limits:
          #     cpu: "0.2"
          #     memory: 100Mi
          #   requests:
          #     cpu: "0.1"
          #     memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: home-website-service
  namespace: default
  labels:
    app: home-website-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: home-website-app
  type: NodePort
